### ISSUE TITLE
download_eggnog_data.py error

### ISSUE THREAD

**Issue by Yu-Wang-uq** [eggnogdb/eggnog-mapper#276] opened 2021-02-04 02:31 UTC
Hi, I got an error when download the database. Please give a hand on that.
Thanks advanced.
Download main annotation database? [y,n] y
Downloading "eggnog.db" at None...
cd None && wget -nH --user-agent=Mozilla/5.0 --relative --no-parent --reject "index.html*" --cut-dirs=4 -e robots=off -O eggnog.db.gz http://eggnogdb.embl.de/download/emapperdb-5.0.1/eggnog.db.gz && echo Decompressing... && gunzip eggnog.db.gz
sh: line 0: cd: None: No such file or directory
Download taxa database? [y,n] y
Downloading "eggnog.taxa.db" at None...
cd None && wget -nH --user-agent=Mozilla/5.0 --relative --no-parent --reject "index.html*" --cut-dirs=4 -e robots=off -O eggnog.taxa.tar.gz http://eggnogdb.embl.de/download/emapperdb-5.0.1/eggnog.taxa.tar.gz && echo Decompressing... && tar -zxf eggnog.taxa.tar.gz && rm eggnog.taxa.tar.gz
sh: line 0: cd: None: No such file or directory
Download diamond database (~4GB after decompression)? [y,n] y
Downloading fasta files " at None...
cd None && wget -nH --user-agent=Mozilla/5.0 --relative --no-parent --reject "index.html*" --cut-dirs=4 -e robots=off -O eggnog_proteins.dmnd.gz http://eggnogdb.embl.de/download/emapperdb-5.0.1/eggnog_proteins.dmnd.gz && echo Decompressing... && gunzip eggnog_proteins.dmnd.gz
sh: line 0: cd: None: No such file or directory
Skipping Pfam database (or already present). Use -P and -f to force download
Skipping MMseqs2 database (or already present). Use -M and -f to force download
No HMMER database requested. Use "-H -d taxid" to download the hmmer database for taxid
Finished.

**Comment by Cantalapiedra** [comment] 2021-02-04 09:21
Duplicate of #275

**Comment by Cantalapiedra** [comment] 2021-02-04 09:23
Hi,

you should be fine running:
`download_eggnog_data.py --data_dir DESTINATION`
where DESTINATION is the directory where you wish to store the downloaded data.
Also defining EGGNOG_DATA_DIR should work:
```
export EGGNOG_DATA_DIR=DESTINATION
download_eggnog_data.py
```

**Closed** 2021-02-04 15:23 UTC
