### ISSUE TITLE
Error with eggnog mapper web tool

### ISSUE THREAD

**Issue by PWTseng** [eggnogdb/eggnog-mapper#331] opened 2021-08-16 06:04 UTC
Hi, 
I used eggnog mapper web tool (http://eggnog-mapper.embl.de/)
After I submit my data

There was an error
[Errno 28] No space left on device

Is any error in web tool?
Thanks

**Comment by Cantalapiedra** [comment] 2021-08-16 10:52
Hi,

we had an issue with the storage device.
We hope that it works fine now.
We are trying to identify the source of the issue, but at least for some time it should be fine now to run jobs.

Sorry for the inconveniences.

Best,
Carlos

**Comment by hzz0024** [comment] 2021-08-16 15:10
Hi,

It seems the web tools do not accept new jobs now. Am I right?

Thanks

**Comment by cdv22** [comment] 2021-08-16 15:26
Hi, but right now all jobs result "status failed", I tried nucleotide and protein sequences and they all failed 
Best,

**Comment by Cantalapiedra** [comment] 2021-08-17 09:31
Hi,

it is weird, I ran test jobs and they finished OK.
Maybe could you share the error status or message, or the job ID (MM_...).

**Comment by cdv22** [comment] 2021-08-18 02:00
my job is Job MM_0x7ufa63 | Status: FAILED 
my job is Job MM_lpdwr4bk | Status: FAILED 

they are exactly the same file submitted to cds or to proteins and both failed. I attached is the input file. 
[2.zip](https://github.com/eggnogdb/eggnog-mapper/files/7003992/2.zip)
in the same way I have 19 other protein files with the same problem.



One recommendation, the web site unfortunately does not indicate why the process fails, it only says that it failed, it would be great if it would say why it failed.

**Comment by Cantalapiedra** [comment] 2021-08-18 09:21
Hi @cdv22 ,

there was a problem in one of the cluster nodes. That is why some jobs were running OK and some failed.
Please, find your job finished at http://eggnog-mapper.embl.de/job_status?jobname=MM_a0u_m4lt
I hope now everyone can run jobs nicely.

We definitely would like to improve the reports about jobs failing, it is a good suggestion. Note that when the failure is due to input data it is usually reported before sending a job email to the user. However, when the job starts running and later fails, it is usually due to a server error.

Sorry for the inconveniences and thank you for your patience and for reporting this.
Please, write back if need further help or your jobs keep failing.

Best,
Carlos

**Comment by Cantalapiedra** [comment] 2021-08-24 07:12
I hope it is working fine for everyone now.
I am closing this. 
Please, reopen or reissue if needed.

**Closed by Cantalapiedra** 2021-08-24 07:12 UTC

**Comment by kirtivel** [comment] 2023-10-04 11:26
Hello, I used eggNOG-mapper from [http://eggnog-mapper.embl.de/](url) and I found that all my jobs were failing. Initially I assumed that it was due to the file size and submitted jobs with files of decreasing size but later understood that it was not so. My job IDs are :
Job MM_6xr1o7l8 
Job MM_cgw943c9
Job MM_aeuquw83
Job MM_7amgfpqk
Job MM_d4ibn89d
Job MM_x657ucz6 
Job MM_1grbs21e
Job MM_cuis8piv

Can you please help me?

**Comment by Cantalapiedra** [comment] 2023-10-05 14:56
Dear @kirtivel ,

Did you check your fasta files? One seems to end with:

>WP_102231992.1
MEFMENINWSGLLTNAGIIILKLIGIIIAFLIVKAIGKKVISSMFNRLQERENISNGRALTLQSLTLNIFSYVLIFIFIVMIFEVFDYNVSALIAGAGVVGLAIGFGAQGLVSDVVTGFFLLLEKQIDVEDYVTVAGFDGIVEQVGLRTTQIRGFDGTLHYVPNREITNVSNHSRGNMRALVDIGISYDDDIDKAIAVLQGVCDKLATENENIMDGPNVLGVQALGSSDVIIRVLAKTKNMEQWAVERELRKAIKEAFDANEIEIPYPHQVNVEKSK                                                                                                                                                                                                                                                                                                                        **Orthogroup_Sequences/OG0009128fa                                                                   0000664 0001750 0001750 00000000274 14431661420 016216 0                                                                                                    ustar lenovo                          lenovo**                                                                                                                                                                                                                 >WP_2359918031MLCITIKSPGKQGQSVQYYPHFEEKHYSNFYNFTYFVDVFFLQSSTVYETIGHLLFKLFDFESNEDNPRDQISFNNAIFKLKEINRPLYKDLNKVKYSDDFQFGVRMRNDIAHNHPPYRIDSGISKSEGLIAFGVGEYTTTNEIKKVMIGLLRSIKATFKVLEKHLRLK

**Comment by kirtivel** [comment] 2023-10-05 15:45
Dear Cantalapiedra,
                                  Thank you for your response. I have no idea how it got there as this is the file created by OrthoFinder. I will check the files before uploading it and try again. Thanks.

**Comment by kirtivel** [comment] 2023-10-05 16:27
Dear Prof. Carlos (@Cantalapiedra ),
                             I submitted a new job - Job MM_d9rx5sfw but this one failed too. I manually looked into the file but did not find the line "**Orthogroup_Sequences/OG0009128fa 0000664 0001750 0001750 00000000274 14431661420 016216 0 ustar lenovo lenovo** " anywhere.  The submission is successful so I assume that nothing is technically wrong with the file itself. Is there any way to validate the fasta files before compressing them into a tar.gz file?  I am kind of new to Linux so please bear with me : (

**Comment by Cantalapiedra** [comment] 2023-10-05 17:07
Dear @kirtivel ,

I checked http://eggnog-mapper.embl.de/MM_d9rx5sfw/

Note that the emapper.out file says "Error running diamond: Error: Error reading input stream at line 20: Invalid character (ASCII 0) in sequence".

I found again weird things from your fasta file: "Orthogroup_Sequences/OG0003533fa                                                                   0000664 0001750 0001750 00000001072 14431661420 016205 0                                                                                                    ustar lenovo                          lenovo  "

Do you know the reason why are those lines within the FASTA file? Because I don't :/

Regarding validation of fasta files, I have never used one, but I guess there are many options out there:

https://github.com/linsalrob/fasta_validator
https://pypi.org/project/py-fasta-validator/
https://www.biostars.org/p/352336/

**Comment by kirtivel** [comment] 2023-10-06 04:45
Dear Prof. Carlos, thank you for your inputs. I really don't know how those lines appear in the uploaded file as I honestly don't see them here. I apologize for the inconvenience, will try to use one of these tools and retry eggNOG-mapper.

**Comment by Cantalapiedra** [comment] 2023-10-06 09:29
You may send me one of your files if you want, so that I can check them and try to run them on eggnog-mapper myself.

**Comment by kirtivel** [comment] 2023-10-06 09:51
Thank you so much professor. Please find the zip file (BIG.zip) attached. Let me know in case of issues. 
[BIG.zip](https://github.com/eggnogdb/eggnog-mapper/files/12829532/BIG.zip)

**Comment by kirtivel** [comment] 2023-10-06 09:55
Thank you so much professor. Please find the zip file (BIG.tar.gz) attached. Let me know in case of issues.
[BIG.tar.gz](https://github.com/eggnogdb/eggnog-mapper/files/12829562/BIG.tar.gz)

**Comment by kirtivel** [comment] 2023-10-06 12:29
Dear Prof. Carlos, (@Cantalapiedra ),
I have identified the problem - the .tar.gz file which I upload for the analysis is the root cause. The unwanted lines appear in the input file when I compress the .fa file into a .tar.gz zip file. I directly uploaded the .fa file for the analysis and it works well now. The instruction to **compress files in a gzip format** was misleading for me I guess. I didn't know that a normal .fa protein file would work just fine. Thank you very much for your support professor :)

**Comment by kirtivel** [comment] 2023-10-10 09:30
Dear Prof. Carlos (@Cantalapiedra )
Thank you for the info Sir. Will keep this in mind before submitting the next job. Thank you for eggNOG-mapper, it is easy to use and the results are so informative. :)

**Comment by Cantalapiedra** [comment] 2023-10-10 10:11
Thank you for your kind words!
Best wishes

**Comment by lizhiming11** [comment] 2025-05-02 00:35
Hello, I used eggNOG-mapper from [http://eggnog-mapper.embl.de/](https://github.com/eggnogdb/eggnog-mapper/issues/url) and I found that all my jobs were failing.

Job MM_jag3i79r Submitted

Can you please help me?

**Comment by Cantalapiedra** [comment] 2025-05-02 08:05
Hi,

If you go to your files (http://eggnog-mapper.embl.de/MM_jag3i79r/) and check your fasta file, you will see that the file is not well formatted, with text lines at the end which are not in fasta format. Please, review your input file and submit it again.

Best,
Carlos
