### ISSUE TITLE
A public online resource problem (502 Bad Gateway) 

### ISSUE THREAD

**Issue by BigNianNGS** [eggnogdb/eggnog-mapper#361] opened 2022-01-21 03:31 UTC
I have visited the public online site: http://eggnog-mapper.embl.de，but it said ”502 Bad Gateway“. 
I have tried switching different networks, but it did not work.
I hope someone can assist with this problem, any help would be greatly appreciated ! Thanks in advance! 

![image](https://user-images.githubusercontent.com/35250400/150460617-75c763d2-5b62-49f1-a1a7-bbc71f570b89.png)

**Comment by Cantalapiedra** [comment] 2022-01-21 08:50
Hi,

One of our servers (physically) crashed and it will take a while to fully recover the service. 
In principle there should be no data loss, only the frontend servers are affected. 
We hope the issue is solved in a few days, but it does not depend on us.

Sorry for the inconveniences.

Best,
Carlos

**Comment by HubbyS** [comment] 2022-01-26 10:19
Hello,

Do you have any updates on this? 

Best,
Roger

**Comment by Cantalapiedra** [comment] 2022-01-26 12:05
Hi,

We are looking to solve this as soon as possible. 
Unfortunately, we cannot say about timings yet.

Sorry for the inconveniences.

Best,
Carlos

**Comment by Cantalapiedra** [comment] 2022-02-03 16:47
Hi,

glad to tell you that http://eggnog-mapper.embl.de/ is working again.
Please, report any problem/bug you may experience.

Sorry for the inconveniences.

Best,
Carlos

**Comment by mstudiva** [comment] 2022-02-03 22:18
Thank you very much, glad you got it fixed!

**Comment by Cantalapiedra** [comment] 2022-02-04 08:03
Thank you @mstudiva !

**Comment by HubbyS** [comment] 2022-02-04 16:50
Thats great, thank you!

**Comment by Cantalapiedra** [comment] 2022-02-17 09:13
Closing this.

Thank you for reporting this and for your patience.

Don't hesitate to re-open or re-issue if needed.

Best,
Carlos

**Closed by Cantalapiedra** 2022-02-17 09:13 UTC
